# Generated by Django 3.2.9 on 2021-11-12 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211112_0512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofilepicture',
            old_name='avatar',
            new_name='img',
        ),
    ]
