# Generated by Django 3.2.9 on 2021-11-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_avatar_userprofilepicture_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfilePicture',
            new_name='Avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
